# Generated by Django 5.1.2 on 2024-10-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icono',
            field=models.ImageField(blank=True, default='media/usuarios/default.png', null=True, upload_to='media/usuarios'),
        ),
    ]
