# Generated by Django 5.1.2 on 2024-10-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contacto_alter_posts_imagen1_alter_posts_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='Contacto',
        ),
    ]
