# Generated by Django 5.1.2 on 2024-10-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table=None,
        ),
    ]
