# Generated by Django 5.1.2 on 2024-10-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='emai',
        ),
    ]
